<a href="https://colab.research.google.com/github/Jamshidbee/learning_data_sciense-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr2 = np.zeros((1,4))


In [ ]:
import numpy as np
arr1 = np.array([[[1,2,3,4],
                  [2,3,4,5],
                  [1,7,8,5]],

                  [[1,2,3,4],
                  [3,2,1,3],
                  [2,3,1,2]]])


In [ ]:
arr1
arr2

array([[0., 0., 0., 0.]])

In [ ]:
arr1.ndim


3

In [ ]:
arr1[0][1,:2]

array([2, 3])

In [ ]:
data1 = np.array([[[1,2,3,4],
                   [5,6,7,8]],
                 
                  [[9,10,11,12],
                  [13,14,15,16],
                  [1,2,3,4]],
                 
                  [[1,2,3,44],
                  [1,2,3,4,5]]])
data1.ndim

<ipython-input-7-107877773272>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data1 = np.array([[[1,2,3,4],


1

In [ ]:
data5 = np.array([[[1,2,3,4],
                   [5,6,7,8]],
                 
                  [[9,10,11,12],
                  [13,14,15,16],
                  [1,2,3,4]],
                 
                 [[1,2,3,44],
                 [1,2,3,4,5]]])
data5.ndim

<ipython-input-8-36b8b9831663>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data5 = np.array([[[1,2,3,4],


1

In [ ]:
data5.ndim

1

In [ ]:
arr2 = np.zeros((1,4))


In [ ]:
arr2


array([[0., 0., 0., 0.]])

In [ ]:
arr2.ndim


2

In [ ]:
data = ["Jamshid","Jamshid","Jamshid"]

In [ ]:
import numpy as np
data = np.array(["Jamshid","Ahmadov","Jamshid"])


In [ ]:
data.ndim

1

In [ ]:
data == "Jamshid"


array([ True, False,  True])

In [ ]:
data1 = np.random.randn(7,4)

In [ ]:
data1
data.ndim

1

In [ ]:
data = np.array(["Jamshid","Ahmadov","Jamshid"])

In [ ]:
bol = np.random.randn(3,2)

In [ ]:
bol


array([[ 0.89382891,  0.45892035],
       [ 0.38088549,  0.90782288],
       [ 0.93899965, -0.09777044]])

In [ ]:
bol[data=="Jamshid"]

array([[ 0.89382891,  0.45892035],
       [ 0.93899965, -0.09777044]])

In [ ]:
y=np.random.randn(3,3)

In [ ]:
y


array([[ 0.36299417, -1.44313513,  1.62480667],
       [ 1.30998776,  0.11169553,  0.83390971],
       [ 1.84107016,  1.51648815,  0.25189199]])

In [ ]:
y[y>0]=1

In [ ]:
y


array([[ 1.        , -1.44313513,  1.        ],
       [ 1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ]])

In [ ]:
print("I AM JUNIOR")

I AM JUNIOR


In [ ]:
print("but I will be Senior")

but I will be Senior


In [ ]:
a=np.random.randn(4,3)

In [ ]:
a


array([[-0.05835555, -1.77838501,  0.56004623],
       [ 0.66956373,  0.66187247,  0.76215424],
       [ 1.59551557,  1.00810089,  0.57384465],
       [ 0.7798823 ,  0.34162307, -0.0541945 ]])

In [ ]:
a.ndim

2

In [ ]:
s= np.arange(1,122)

In [ ]:
s

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121])

In [ ]:
print(s)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121]


In [ ]:
s=np.array(s)

In [ ]:
import numpy as np

In [ ]:
numbers=np.arange(12).reshape(4,3)

In [ ]:
numbers

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
numbers.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
k=numbers

In [ ]:
k


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
numbers

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
numbers.swapaxes(1,0)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
numbers.swapaxes(0,1)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
numbers.swapaxes(1,1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a=int(input())

121


In [ ]:
np.sqrt(numbers)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
np.exp(numbers)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
arr=np.array([1,2,3,4,5])
arr1=np.array([2,2,2,2,2])

In [ ]:
np.power(arr,arr1)

array([ 1,  4,  9, 16, 25])

In [ ]:
np.mod(arr, arr1)

array([1, 0, 1, 0, 1])

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,1,1,1,1,1])
arr2 = np.array([3,4,5,6,7,8])

In [ ]:
re = np.where(arr1>4, arr1, arr2)

In [ ]:
re

array([3, 4, 5, 6, 7, 8])

In [ ]:
re = np.where(arr2>4, arr1, arr2)
re

array([3, 4, 1, 1, 1, 1])

In [ ]:
g=np.array([1,0,1,1,1,1])


In [ ]:
re=np.where(g == 1,arr1,arr2)

In [ ]:
re

array([1, 4, 1, 1, 1, 1])

In [ ]:
re.ndim

1

In [ ]:
# r=int(input())
# if r>10:
#   print("HELLO WORLD")

In [ ]:
arr1.ndim

1

In [ ]:
numbers.ndim

2

In [ ]:
array=np.arange(10)

In [ ]:
m = array*2

In [ ]:
m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
m
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array1=np.arange(10,20)

In [ ]:
array1*array

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [ ]:
nm=array*array1

In [ ]:
nm

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [ ]:
nm[-1]

171

In [ ]:
nm[4] =0
nm

array([  0,  11,  24,  39,   0,  75,  96, 119, 144, 171])

In [ ]:
array.mean()

4.5

In [ ]:
array.mean(axis=0)

4.5

In [ ]:
array=np.arange(12).reshape(3,4)

In [ ]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array.mean(axis=0)

array([4., 5., 6., 7.])

In [ ]:
array.mean(axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
import numpy as np


In [ ]:
import numpy as np

In [ ]:
arr=np.random.rand(6)

In [ ]:
arr

array([0.45397415, 0.45857   , 0.01609949, 0.44051729, 0.76916441,
       0.63513045])

In [ ]:
arr.sort()
arr

array([0.01609949, 0.44051729, 0.45397415, 0.45857   , 0.63513045,
       0.76916441])

In [ ]:
arr=np.random.randn(11)

In [ ]:
arr

array([ 0.70097467, -0.62124703, -0.92557056, -0.72985639, -0.22805821,
        0.5950006 ,  1.01280082,  1.18430958,  0.43674334,  0.4427311 ,
        0.47849788])

In [ ]:
arr1 = -np.sort(-arr)

In [ ]:
arr1

array([ 1.18430958,  1.01280082,  0.70097467,  0.5950006 ,  0.47849788,
        0.4427311 ,  0.43674334, -0.22805821, -0.62124703, -0.72985639,
       -0.92557056])

In [ ]:
print(arr1.sort())


None


In [ ]:
print(-arr1)

[ 0.92557056  0.72985639  0.62124703  0.22805821 -0.43674334 -0.4427311
 -0.47849788 -0.5950006  -0.70097467 -1.01280082 -1.18430958]


In [ ]:
print(arr1)

[-0.92557056 -0.72985639 -0.62124703 -0.22805821  0.43674334  0.4427311
  0.47849788  0.5950006   0.70097467  1.01280082  1.18430958]


In [ ]:
arr23=np.random.randn(2,4)

In [ ]:
arr23


array([[ 0.41295995,  0.03698622,  0.24888046, -0.67775038],
       [ 2.29805718, -0.75822824, -0.20148457,  0.30704439]])

In [ ]:
row = np.sort(arr23, axis=0)

In [ ]:
row

array([[ 0.41295995, -0.75822824, -0.20148457, -0.67775038],
       [ 2.29805718,  0.03698622,  0.24888046,  0.30704439]])

In [ ]:
row=np.sort(arr23, axis=1)

In [ ]:
row

array([[-0.67775038,  0.03698622,  0.24888046,  0.41295995],
       [-0.75822824, -0.20148457,  0.30704439,  2.29805718]])

In [ ]:
arr1 = np.array(["Jamshid","Jamshid","Ahmadov"])
arr1

array(['Jamshid', 'Jamshid', 'Ahmadov'], dtype='<U7')

In [ ]:
np.unique(arr1)

array(['Ahmadov', 'Jamshid'], dtype='<U7')

In [ ]:
arr2=np.array(["Jamshid","1212"])

In [ ]:
np.in1d(arr2,arr1)

array([ True, False])

In [ ]:
k = np.setdiff1d(arr2,arr1)
k1 = np.setdiff1d(arr1,arr2)

In [ ]:
k,k1

(array(['1212'], dtype='<U7'), array(['Ahmadov'], dtype='<U7'))

In [ ]:
arr=np.arange(56)
arr_2=np.arange(34)

In [ ]:
np.save("datas",arr)

In [ ]:
np.savez("arrays", a=arr, b=arr_2)

In [ ]:
array_basic = np.load("arrays.npz")

In [ ]:
array_basic['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [ ]:
import numpy as np
ary=np.array([1,2,3,4,5,8])
ary=ary+1
print(ary[1])

3


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.itemsize)

8


In [ ]:
array_nig = np.arange(1,1000,3)

In [ ]:
array_nig[11]

nothing

In [ ]:
n=int(input("Enter: "))
print(array_nig[n-1])

In [ ]:
import numpy as np

In [ ]:
ran = np.arange(6)

In [ ]:
ran

array([0, 1, 2, 3, 4, 5])

In [ ]:
ran.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])